### ISSUE TITLE
about multi-GPU

### ISSUE THREAD

**Issue by DipDipPotatoChips** [tianweiy/CenterPoint#223]
It cost me a week to train a model in nu-scenes.
When I tryed  to use 2 gpus,it seemed that the program is stuck，the GPU usage was low and it did't change anyway.I alomost waited for 5 days but  it still did't complete in the end,so I used ctrl+c to shut it down.But after that the GPU usage was still occupied.I have to reboot the device.
When it worked normally with 1 GPU,the terminal printed some message about training process.But it won't print those when with 2 GPUs.So I believe that the program did't work.
The device is 3090:
3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0]
torch_version: 
1.8.0+cu111
torchvision_version: 
0.9.0+cu111
cuda_version: 
11.1

And I used this to train:
python -m torch.distributed.launch --nproc_per_node=2 ./tools/train.py configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py

Sorry for my pool English.I don't know how to show a picture.

**Comment by tianweiy** [comment]
What spconv version ? You can also try multigpu with pointpillar configs to see what is the error. I have no issue with multigpu on my servers

**Comment by tianweiy** [comment]
When it worked normally with 1 GPU,the terminal printed some message about training process.But it won't print those when with 2 GPUs.So I believe that the program did't work.

There will be a log file inside the folder in work_dirs. If there is no content there, then it is probably stuck and never begin training

**Comment by DipDipPotatoChips** [comment]
> 

spconv 1.2.1

**Comment by tianweiy** [comment]
Could you try if pointpillar + 2 gpu work ?

**Comment by DipDipPotatoChips** [comment]
> When it worked normally with 1 GPU,the terminal printed some message about training process.But it won't print those when with 2 GPUs.So I believe that the program did't work.
> 
> There will be a log file inside the folder in work_dirs. If there is no content there, then it is probably stuck and never begin training

I have seen that.when training voxel models,for the first hour or so after the training starts, some log files are output.But not after that.Now I'm trying the pp.

**Comment by tianweiy** [comment]
ok, I am able to train both pp / VoxelNet using the master code under similar environments. 

torch_version:
1.9.0+cu111
torchvision_version:
0.10.0+cu111
cuda_version:
11.1

Titan RTX / Titan X

**Comment by DipDipPotatoChips** [comment]
> ok, I am able to train both pp / VoxelNet with multiple gpus using the master code under similar environments.
> 
> torch_version: 1.9.0+cu111 torchvision_version: 0.10.0+cu111 cuda_version: 11.1
> 
> Titan RTX / Titan X

Maybe I should reinstall a environment，but now the spconv has updated to 2.0，can I just use this？

**Comment by DipDipPotatoChips** [comment]
I think I have found the problem.
I installed the spconv-1.0 by accident(It was 1.2 before),and it printed the errors when training:
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 132, in main
    logger=logger,
  File "/home/ruidong/workplace/CenterPoint/det3d/torchie/apis/train.py", line 269, in train_detector
    model = apex.parallel.convert_syncbn_model(model)
NameError: name 'apex' is not defined

 It print the above message without ending and occupied the GPU usage. 
It's actually going to print “no tensorflow！” “no apex！”every time I trained it.But it won't print any errors with spconv-1.2,so I ignored it.
The question is that I have installed the apex accoding to install.md.
Why it reported this error?
23333

**Comment by DipDipPotatoChips** [comment]
Finally I solve by accoding this [https://github.com/pytorch/pytorch/issues/51959](url)

**Comment by DipDipPotatoChips** [comment]
Finally I solve by accoding this #51959

**Comment by DipDipPotatoChips** [comment]
Finally I solve according to https://github.com/pytorch/pytorch/issues/51959

**Comment by tianweiy** [comment]
Maybe I should reinstall a environment，but now the spconv has updated to 2.0，can I just use this？

People told me spconv 2.0 will make the result worse by 1 to 2 points. I don't have time to test this so I would suggest using 1.2.1 for now
